apiVersion: v1
kind: ConfigMap
metadata:
  name: v3io-presto-script
  labels:
    app: {{ template "presto.v3io.name" . }}
    chart: {{ template "presto.v3io.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  v3io-presto.sh: |
    #!/bin/bash
    set -e

    export IGZ_DATA_CONFIG_FILE="$IGUAZIO_JAVA/conf/v3io.conf"

    LOOKUP_URL={{ printf "http://%s:%d/%s" .Values.v3io.daemonLookupServiceHost (int .Values.v3io.daemonLookupServicePort) .Values.v3io.daemonLookupServicePath }}
    LOCAL_V3IO_DAEMON=$(curl --silent $LOOKUP_URL/$CURRENT_NODE_IP)
    sed -i "s/CURRENT_NODE_IP/$LOCAL_V3IO_DAEMON/g" $IGZ_DATA_CONFIG_FILE

    /bin/bash -x /etc/config/presto/docker-presto.sh

---
