presto:
  server:
    log:
      com.facebook.presto: INFO
      io.iguaz.v3io: DEBUG
      io.iguaz.v3io.daemon: INFO
  config:
    mapPath: /etc/config/presto

  image:
    repository: iguaziodocker/presto
    tag: 0.189-1.5.2
    command: /etc/config/v3io/v3io-presto.sh

  environment:
    - name: CURRENT_NODE_IP
      valueFrom:
        fieldRef:
          fieldPath: status.hostIP

  volumes:
    coordinator:
      - name: shm
        path:
          hostPath:
            path: /dev/shm
        mount: /dev/shm
      - name: daemon-comm
        path:
          hostPath:
            path: /tmp/dayman
        mount: /tmp/dayman
      - name: v3io-presto-config-volume
        path:
          configMap:
            name: v3io-presto-script
        mount: /etc/config/v3io
    worker:
      - name: shm
        path:
          hostPath:
            path: /dev/shm
        mount: /dev/shm
      - name: daemon-comm
        path:
          hostPath:
            path: /tmp/dayman
        mount: /tmp/dayman
      - name: v3io-presto-config-volume
        path:
          configMap:
            name: v3io-presto-script
        mount: /etc/config/v3io

v3io:
  daemonLookupServiceHost: local-registry
  daemonLookupServicePort: 8080
  daemonLookupServicePath: registry/daemon